from vk.exceptions import VkAPIError


class AuthorizationError(VkAPIError):
    pass

